### ISSUE TITLE
save_binder not defined

### ISSUE THREAD

**Issue by avilella** [ohuelab/Solubility_AfDesign#1]
See error below from running the Colab:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-1-6f14e3d14623>](https://localhost:8080/#) in <module>()
----> 1 save_binder(model, f"Solubility_AfDesign_{solubility_index}_{pdb_id}_{chain}.pdb")

NameError: name 'save_binder' is not defined
```

**Comment by blacktanktop** [comment]
Hi!
Perhaps you are running Jupter Notebook "locally". (Because "https://localhost:8080/" can be seen in the error message.)
This notebook is designed to be run in "Colab", not in your local Jupyter Notebook environment.

So, if you want to run it locally, please rewrite the PATH settings of each cell and the file input/output code appropriately.
and also please change the module PATH appropriately on your environment.

The easiest way not to change the PATH is to copy and paste all the functions listed in design_util.py into the appropriate cells of the Notebook in design.ipynb.

**Comment by avilella** [comment]
I am running it in Colab (opened by clicking the colab link)
https://colab.research.google.com/github/ohuelab/Solubility_AfDesign/blob/solubility/design.ipynb#scrollTo=7UNRbURYr9k5

**Comment by avilella** [comment]
Silly idea, but could it be that there is no new-line after the last statement in the defining function?
https://github.com/ohuelab/Solubility_AfDesign/blob/9ea26ab50e08e5bdc440c90d608ce68d4ed92a46/design_util.py

**Comment by blacktanktop** [comment]
I have confirmed that save_binder can be run on Colab.
Are you able to output the model, aimation movie and get best sequence?
Basically, 
Target protein, binder settings and weight settings
and then run the program with "Runtime -> Run all".
(save_binder in design_util.py is downloaded and loaded in the Install and import libraries cells)

**Comment by avilella** [comment]
All the steps except the last one work in the Colab. See screenshot with the default input parameters, then "Runtime -> Run all":

![image](https://user-images.githubusercontent.com/158007/169048002-9918b5f5-e9bc-4507-acb9-ca45917f9001.png)

**Comment by blacktanktop** [comment]
That's strange. When I run the same thing it behaves properly.
<img width="925" alt="スクリーンショット 2022-05-18 22 29 11" src="https://user-images.githubusercontent.com/7370243/169050341-b6ba4a6b-8e9f-4882-b698-40f0cfe02397.png">

I don't know why, so once you create a cell before the save_binder() cell, copy and paste all the contents of design_util.py, run it, and try to run the save_binder() cell.

**Comment by blacktanktop** [comment]
Resolved?
I'll close it now.

**Comment by avilella** [comment]
Still the same, I am trying with Firefox instead of Chrome, just in case.

**Comment by avilella** [comment]
Somehow it works in Firefox. Where would the file reside after completing the save step? In Google Drive? Should it come up as a download from the browser?

**Comment by blacktanktop** [comment]
I'm glad you were able to execute it well for now. To download the file, click on the file symbol on the left side of Colab in your browser, as shown in the image, and you will see the file. (The same goes for .mp4 video files.)
(Colab's internal PATH is under /content).

<img width="925" alt="169050341-b6ba4a6b-8e9f-4882-b698-40f0cfe02397" src="https://user-images.githubusercontent.com/7370243/169626354-1bd3e30c-9812-42d8-9a36-148aca0af9a5.png">

**Comment by avilella** [comment]
I can see the files under `/content` now, thanks. It works flawlessly with Firefox, so I'll stick to that. Thanks!
